title: Companion App - Your smartphone on your PC
description: <a href="https://akamsyourpcc.com/recommendation/"><img src="/get-st.png"alt="Companion App"/></a>
google_analytics: G-H0VV6PT1JS
google_webmaster: <meta name="google-site-verification" content="COpfpX8_PYqIyUnPayrPX5t8iK7b9oxIWbEKtt_sYhY" />
theme: jekyll-theme-cayman
